spin_version = "1"
name = "sample-rust-spin"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[[component]]
id = "hello"
source = "/app/sample_rust_spin.wasm"
[component.trigger]
route = "/"