name: sample-rust-spin
services:
- name: spin
  dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: bojand/sample-rust-spin
  health_check:
    http_path: /healthz